### ISSUE TITLE
Sometimes /me goes global.

### ISSUE THREAD

**Issue by izvanilla** [Sheamle/3dme#3]
Sometimes /me goes global.
EG : 1 player does '/me test'
it appears on everyone.

**Comment by boomiiee** [comment]
cause someones in a split lol

**Comment by rex2630** [comment]
I think that this is really big problem. Does anybody know fix, please?

**Comment by ELF0001** [comment]
yes you can just add a check if it is using the own players position i did that when i created a vrp2 id head display

**Comment by Sheamle** [comment]
Should be solved with latest update.
